name: Synopsys - Actions

on:
  workflow_dispatch

jobs:
  Synopsys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          
      - name: Polaris Scan (SAST)
        uses: synopsys-sig/synopsys-action@v1.2.0
        with:
          polaris_serverUrl: ${{ secrets.BRIDGE_POLARIS_SERVERURL }}
          polaris_accessToken: ${{ secrets.BRIDGE_POLARIS_ACCESSTOKEN }}
          polaris_application_name: "FCBR"
          polaris_project_name: "POC"
          polaris_assessment_types: "SAST"            
        
